{% set name = "unyt" %}
{% set version = "2.0.0" %}
{% set sha256 = "635d52685fe5f2327d5a232ed38811157b3a1dd686f5dc472c2c4ae6ff9d3aff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.13.0
    - sympy

test:
  imports:
    - unyt

about:
  home: http://github.com/yt-project/unyt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Handle, manipulate, and convert data with units in Python'
  doc_url: http://unyt.readthedocs.io/
  dev_url: https://github.com/yt-project/unyt

extra:
  recipe-maintainers:
    - ngoldbaum
