{% set name = "unyt" %}
{% set version = "1.0.6" %}
{% set sha256 = "b613a759972b51f1c28f71f8ab6cb0886498534f2270bbdc7eb8c47597a3f415" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # we can enable this when we drop py27 or when conda-forge
  # lets you do this with optional py27 dependencies
  # noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.13.0
    - sympy
    - six
    - backports.functools_lru_cache  # [py27]

test:
  imports:
    - unyt

about:
  home: http://github.com/yt-project/unyt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Handle, manipulate, and convert data with units in Python'
  doc_url: http://unyt.readthedocs.io/
  dev_url: https://github.com/yt-project/unyt

extra:
  recipe-maintainers:
    - ngoldbaum
