{% set name = "unyt" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 771582a87f1e521c9b62f7ca269b1965c0f77b479f7a063a51e8cef8b4cae51d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=7.0.1
    - flit-core >=3.11,<4
  run:
    - python
    - numpy >=1.21.3,<3.0
    - sympy >=1.9.0
    - packaging >=20.9

test:
  requires:
    - pip
    - pytest
  imports:
    - unyt
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs unyt.tests

about:
  home: https://github.com/yt-project/unyt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Handle, manipulate, and convert data with units in Python
  description: |
    A package for handling numpy arrays with units.
    Often writing code that deals with data that has units can be confusing.
    A function might return an array but at least with plain NumPy arrays,
    there is no way to easily tell what the units of the data are without somehow knowing them prior.
    The unyt package (pronounced like "unit") provides a subclass of NumPy's
    ndarray class that knows about units.
  doc_url: https://unyt.readthedocs.io
  dev_url: https://github.com/yt-project/unyt

extra:
  recipe-maintainers:
    - jzuhone
    - ngoldbaum
    - neutrinoceros
