{% set name = "unyt" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1d6f481186c663b2631fe129e82abdf0aed61a93a70662040020aabe016384b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # test_wrapping_completeness fails with numpy>=2.1 since the cumulative_prod (introduced in numpy 2.1)
    # array function was added after 3.0.3, this will likely be fixed in 3.0.4.
    # Restricting upper-bound for now, see https://github.com/yt-project/unyt/pull/512
    - numpy >=1.19.3,<2.1 # [py<313]
    # Making an exception for python 3.13 since numpy>=2.1 is the only option
    # This means that this package *may* misbehave for python 3.13 until v3.0.4 is released
    - numpy >=1.19.3,<3.0 # [py>=313]
    - sympy >=1.7
    - packaging >=20.9

# Skip failing tests for python 3.13 because of the use of numpy>=2.1
{% set tests_to_skip = "" %}
{% set tests_to_skip = tests_to_skip + "test_wrapping_completeness or " %} # [py>=313]
{% set tests_to_skip = tests_to_skip + "test_known_arguments" %} # [py>=313]
test:
  source_files:
    - unyt/tests
  requires:
    - pip
    - pytest
  imports:
    - unyt
  commands:
    - pip check
    - pytest unyt/tests -v -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/yt-project/unyt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Handle, manipulate, and convert data with units in Python
  description: |
    A package for handling numpy arrays with units.
    Often writing code that deals with data that has units can be confusing. 
    A function might return an array but at least with plain NumPy arrays, 
    there is no way to easily tell what the units of the data are without somehow knowing them prior.
    The unyt package (pronounced like "unit") provides a subclass of NumPy's 
    ndarray class that knows about units.
  doc_url: https://unyt.readthedocs.io/
  dev_url: https://github.com/yt-project/unyt

extra:
  recipe-maintainers:
    - jzuhone
    - ngoldbaum
    - neutrinoceros
