travis:
  secure:
    BINSTAR_TOKEN: RTeDp164aS3xhDMFN4GGLJUmsDAoow7itqHs0C9Yj6BiSKrDrgZJY1Yd7fHsFqgTjuKOI6/j+glBfB0RHEqykj872Jb2mzMX9bNWnvhK8RVMOZa44oo304cp00NGskMi/xiN9cED7YuF3brfzPyK6TKQCbyewAU0m9J3f8vAREg0KFPh7Z5bE7l9WxvNw0p94wWuX7j8ieyyRxEmjWJQfpA1COzcUauDNO6HoiDOiPxb8dooeBN543wcO2YgNYIcr/nBao9I2gKpVzbvxyZV0xh3epiM4FyP7csRBD7Nxempx9vqGXCPAh0RU/oqB4Sqq7D0wNhIwZ8Gr5Qo1+NnAQ1GhUvBfR81N7HUU24BS5iVGiH8Il+ZCR8ZpB9tYGtfUad35vIFASxcbefgoe9ai+0JjW420lR31v2EJ34uGaP7XpQrQzC7lAHtjaq4dazFZHCBRmVyGERj10fJgxZ0oQGzOLnpVPBXAZ/uFdu2sSLK4CyvSl91gAEJ8oKe2i7K/8Dafs4MgUEt79QZlfdFw7Z0v1bySC3SJzpYL67ntTFKO4kZvC7mY0EsdpeWZnXFLNyXkUXZwuEsWvegDRyAu0+Ohci+CQCJBE2EEiLaM7m/WpRlNmQjZFKBtllAqyf4vfLDS1Z6mnBRaPnP7/FHZf0Qq//0sSOfr0EsEab2L9M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
